# Generated by Django 5.2.9 on 2026-04-13 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawProvision',
            fields=[
                ('provision_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('law_name', models.CharField(help_text='e.g., Constitution of Tanzania, 1977', max_length=255)),
                ('article_no', models.CharField(help_text='e.g., 15 or Section 4(2)', max_length=50)),
                ('category', models.CharField(help_text='e.g., Basic Rights, Criminal, Labor', max_length=100)),
                ('content_official_en', models.TextField(verbose_name='Official English Content')),
                ('content_official_sw', models.TextField(verbose_name='Official Swahili Content')),
                ('plain_summary_en', models.TextField(verbose_name='Plain English Summary (Mtaani)')),
                ('plain_summary_sw', models.TextField(verbose_name='Plain Swahili Summary (Mtaani)')),
                ('good_conduct', models.TextField(verbose_name='Good Conduct Suggestions')),
                ('penalty_summary', models.TextField(blank=True, null=True, verbose_name='Penalty Summary')),
                ('scope', models.CharField(choices=[('national', 'National'), ('regional', 'Regional'), ('municipal', 'Municipal')], default='national', max_length=20)),
                ('region', models.CharField(blank=True, help_text='Required if scope is regional or municipal', max_length=100, null=True)),
                ('last_amended', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Law Provision',
                'verbose_name_plural': 'Law Provisions',
                'unique_together': {('law_name', 'article_no')},
            },
        ),
    ]
