# Generated by Django 6.0.4 on 2026-04-13 20:15

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0002_lawprovision_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawprovision',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
