# Generated by Django 5.2.9 on 2026-04-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
