# Generated by Django 5.2.9 on 2026-04-13 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAidOrganization',
            fields=[
                ('org_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('human_rights', 'Human Rights'), ('labour', 'Labour Law'), ('family', 'Family & Inheritance'), ('criminal', 'Criminal Defence'), ('land', 'Land Disputes'), ('general', 'General Legal Aid')], max_length=50)),
                ('description', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legal Aid Organization',
                'verbose_name_plural': 'Legal Aid Organizations',
            },
        ),
    ]
