# Generated by Django 5.2.9 on 2026-04-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100, unique=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_requested', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Topic',
                'verbose_name_plural': 'Search Topics',
                'ordering': ['-count'],
            },
        ),
    ]
